import localFont from "next/font/local";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { ReservedProvider } from "@/context/ReservedContext";
import Navbar from "@/components/layout/Navbar";
import { UserInfoProvider } from "@/context/UserInfoContext";

const yekanBakh = localFont({
  src: "./fonts/YekanBakhMedium.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "سامانه رزرو نوبت",
  description: "Generated by create next app",
};
export const viewport = {
  themeColor: "#ffd39a",
};
export default function RootLayout({ children }) {

  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${yekanBakh.variable} ${geistMono.variable} antialiased bg-slate-50 `}
      >
        <ReservedProvider>
          <UserInfoProvider>
            <ToastContainer
              position="top-center"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick={true}
              rtl={true}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
              limit={2}
            />
            <Navbar />
            {children}
          </UserInfoProvider>
        </ReservedProvider>
      </body>
    </html>
  );
}




{/* <Toaster
position="top-center"
reverseOrder={false}
gutter={1}
containerClassName=""
containerStyle={{}}
toastOptions={{
  // Define default options
  className: 'font-semibold',
  duration: 5000,
  removeDelay: 1000,
  style: {
    background: '#fff',
    color: '#363636',
  },

  // Default options for specific types
  success: {
    duration: 3000,
    iconTheme: {
      primary: 'green',
      secondary: 'white',
    },
  },
}}
/> */}
