import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layout/Header";
import { Toaster } from 'react-hot-toast';
import { ToastContainer } from "react-toastify";

const yekanBakh = localFont({
  src: "./fonts/YekanBakhMedium.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "سامانه رزرو نوبت",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${yekanBakh.variable} ${geistMono.variable} antialiased `}
      >
        <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={true}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}




{/* <Toaster
position="top-center"
reverseOrder={false}
gutter={1}
containerClassName=""
containerStyle={{}}
toastOptions={{
  // Define default options
  className: 'font-semibold',
  duration: 5000,
  removeDelay: 1000,
  style: {
    background: '#fff',
    color: '#363636',
  },

  // Default options for specific types
  success: {
    duration: 3000,
    iconTheme: {
      primary: 'green',
      secondary: 'white',
    },
  },
}}
/> */}
